Repository gdsc-uba/linktree, pull requests merged in 2023-10, with the labels that each got.

#77 feat: Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#89 feat: add KajiAime linktree
  linktree/KajiAime.json
Labels: hacktoberfest-accepted

#88 feat: add mofirojean linktree
  linktree/mofirojean.json
Labels: hacktoberfest-accepted

#87 feat: add YopaNelly linktree
  linktree/YopaNelly.json
Labels: hacktoberfest-accepted

#92 feat: add Fombi-Favour linktree
  linktree/Fombi-Favour.json
Labels: hacktoberfest-accepted

#91 feat: add bimme2audrey Linktree
  linktree/bimme2audrey.json
Labels: hacktoberfest-accepted

#90 feat: add raiyan parwez linktree
  linktree/raiyanparwez.json
Labels: hacktoberfest-accepted

#93 feat: added vishal-kumar-singh linktree
  linktree/vishal-kumar-singh.json
Labels: hacktoberfest-accepted

#94 feat: add aayushpaigwar linktree
  linktree/aayushpaigwar.json
Labels: documentation, good first issue, hacktoberfest-accepted

#95 feat: added shaileshthakur1 linktree
  linktree/shaileshthakur.json
Labels: good first issue, hacktoberfest-accepted

#96 feat: add massablaise linktree
  linktree/massablaise.json
Labels: hacktoberfest-accepted

#101 my linktree contribution
  linktree/jobs-code.json
Labels: hacktoberfest-accepted

#97 feat: add shenyuygoodness linktree
  linktree/shenyuygoodness.json
Labels: hacktoberfest-accepted
